version: '3'

services:
  telegram-consumer:
    container_name: telegram-consumer
    image: telegram-consumer
    environment:
      - ALPHABET_RANGE=a-m
    networks:
      - kafka-network
      
  telegram-producer:
    container_name: telegram-producer
    image: telegram-producer
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true